# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'Myotera' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Myotera
  pod 'ScrollableGraphView'
  
  # Pods for ChartsTutorial
  pod 'Charts'
  
  #Movesense
  pod 'Movesense', :git => 'https://www.bitbucket.org/suunto/movesense-mobile-lib.git'

  target 'MyoteraTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MyoteraUITests' do
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '5.0'
      config.build_settings['DEBUG_INFORMATION_FORMAT'] = 'dwarf'
    end
  end
end
