# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'myotera' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for myotera
  pod 'Movesense', :git => 'https://www.bitbucket.org/suunto/movesense-mobile-lib.git'

end

# Update all targets to Swift version 5.0 to stop Xcode version upgrade nagging
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '5.0'
      config.build_settings['DEBUG_INFORMATION_FORMAT'] = 'dwarf'
    end
  end
end
